# Site settings
name: 学习笔记
email: qparrow1996@gmail.com
author: qin piao
url: https://qparrow.github.io/learn-k8s-sourcecode/
resume_site: https://qparrow.github.io/learn-k8s-sourcecode/
github: https://github.com/qparrow/
baseurl: '/learn-k8s-sourcecode'
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qparrow

# Build settings
markdown: kramdown

